version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y
  build:
    commands:
      - echo "Building the application..."
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo "Creating deployment package..."
      - zip -r deployment-package.zip . -x "*.git*"

artifacts:
  files:
    - deployment-package.zip
